Created unit tests for document database table
CMU-313/fall22-hw3-jabby pull request #13
Opened 2022-09-30 23:44 UTC by awutis

Resolves #10 
**Description:** 
- created unit tests to test existence of each of the new columns created by creating a new document, assigning a value to each of the corresponding columns, and asserting equality 
- modified Document DAO sql query to correct bug (previously missing a ",")

**Testing:**
Updated database by running ```mvn jetty:run```
Ran ```mvn test``` and all tests passed

2022-10-01 00:39 UTC, jakezych commented
Looks like I'm getting a test failure in TestJpa.Java when I run mvn test. Do the tests pass on your end?

2022-10-01 00:55 UTC, awutis commented
> Looks like I'm getting a test failure in TestJpa.Java when I run mvn test. Do the tests pass on your end?
> ![Screen Shot 2022-09-30 at 8 40 46 PM](https://user-images.githubusercontent.com/56098501/193376241-d0c59215-ebbe-4b69-a060-4a1c38be9c20.png)

This is weird, when I ran mvn:test it seemed to work, let me look into this
<img width="1117" alt="Screen Shot 2022-09-30 at 20 55 50" src="https://user-images.githubusercontent.com/79778718/193376822-a7312cf2-ec50-48e9-a62c-6d993189d0ca.png">

2022-10-01 01:05 UTC, jakezych requested changes

2022-10-01 01:05 UTC, jakezych commented on docs-core/src/test/java/com/sismics/docs/core/dao/jpa/TestJpa.java
> +        document.setNum_reviews(0);
Test fails on line 48 because document is not associated with a user id when it is created. Here's what I came up with as a fix 

```        
document.setCreateDate(new Date());
document.setLanguage("english");
document.setUserId(id);
documentDao.create(document, id);

2022-10-01 01:30 UTC, awutis commented on docs-core/src/test/java/com/sismics/docs/core/dao/jpa/TestJpa.java
> +        document.setNum_reviews(0);
Thank you so much - addressed in latest commit. Please let me know if it works

2022-10-02 03:04 UTC, jakezych commented
Looks good to me. Merging

2022-10-02 03:04 UTC, merged